name: Build & Deploy to Cloud Run

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: github-cicd-461810
          version: "latest"

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      - name: Build Docker image
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          docker build -t asia-southeast1-docker.pkg.dev/github-cicd-461810/nodejs-github-action-cloud-run/nodejs-github-action-cloud-run:$TAG_NAME -f Dockerfile.prod .

      - name: Push Docker image to Artifact Registry
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          docker push asia-southeast1-docker.pkg.dev/github-cicd-461810/nodejs-github-action-cloud-run/nodejs-github-action-cloud-run:$TAG_NAME

      - name: Deploy to Cloud Run
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          gcloud run deploy nodejs-github-action-cloud-run \
            --image asia-southeast1-docker.pkg.dev/github-cicd-461810/nodejs-github-action-cloud-run/nodejs-github-action-cloud-run:$TAG_NAME \
            --region asia-southeast1 \
            --platform managed \
            --allow-unauthenticated \
            --quiet
