name: Build & Deploy to Cloud Run

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  TAG_NAME: ${{github.ref_name}}
  REGION: "asia-southeast1"
  REPOSITORY: "nodejs-github-action-cloud-run"
  IMAGE_NAME: "nodejs-github-action-cloud-run"
  PROJECT_ID: "github-cicd-461810"
  SERVICE_NAME: "nodejs-github-action-cloud-run"
  DOCKERFILE_NAME: "Dockerfile.prod"
  IMAGE_URI: $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$TAG_NAME

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{env.PROJECT_ID}}
          version: "latest"

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev
      - name: Build Docker image
        run: |
          docker build -t ${{env.IMAGE_URI}} -f ${{env.DOCKERFILE_NAME}} .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{env.IMAGE_URI}}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{env.SERVICE_NAME}} \
            --image ${{env.IMAGE_URI}} \
            --region ${{env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --quiet
